# general
PLATFORM_NAME: "My platform" 
OPENEDX_SECRET_KEY: secret 
CONTACT_EMAIL: contact@abc.com
ENABLE_HTTPS: true
LANGUAGE_CODE: vi
RUN_REDIS: true

DX_PLATFORM_VERSION: open-release/olive.master # ???

ID: id

JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----
...
  -----END RSA PRIVATE KEY-----'

# lms
LMS_HOST: abc.com 
# MYSQL_HOST: 34.87.69.198
# MYSQL_PORT: 3306
OPENEDX_MYSQL_DATABASE: openedx
OPENEDX_MYSQL_PASSWORD: openedx
MYSQL_ROOT_PASSWORD: root
MYSQL_ROOT_USERNAME: root
MONGODB_DATABASE: dbname

# cms
CMS_HOST: studio.abc.com
CMS_OAUTH2_SECRET: secret

# auth
MFE_AUTHN_MFE_APP:
  name: authn
  port: 1999
  repository: https://github.com/username/frontend-app-authn
  version: staging

# edx-platform
EDX_PLATFORM_REPOSITORY: https://github.com/username/edx-platform
EDX_PLATFORM_VERSION: staging

# discussion
MFE_DISCUSSIONS_MFE_APP:
  name: discussions
  port: 2002
  repository: https://github.com/username/frontend-app-discussions
  version: staging

# frontend-app-learning
MFE_LEARNING_MFE_APP:
  name: learning
  port: 2000
  repository: https://github.com/username/frontend-app-learning.git
  version: staging

# notes
NOTES_MYSQL_PASSWORD: root
NOTES_OAUTH2_SECRET: secret
NOTES_SECRET_KEY: secret

# plugins
PLUGINS:
- forum
- mfe
- myplugin
- notes
PLUGIN_INDEXES:
- https://overhang.io/tutor/main

# smtp
SMTP_HOST: smtp.sendgrid.net
SMTP_PASSWORD: pass
SMTP_PORT: 587
SMTP_USERNAME: username
